kind: pipeline
name: default


steps:  
# - name: docker-db
#   image: plugins/docker
#   settings:
#     dockerfile: db/Dockerfile
#     username:
#       from_secret: hub_username
#     password:
#       from_secret: hub_password
#     repo: turik207/kube-db

- name: docker-web  
  image: plugins/docker
  settings:
    dockerfile: web/Dockerfile
    username:
      from_secret: hub_username
    password:
      from_secret: hub_password
    repo: turik207/kube-web
