kind: pipeline
name: default

# steps:
# - name: build
#   image: postgres:10.0-alpine
#   commands:
#     - cp db/words.sql /docker-entrypoint-initdb.d/
steps:  
- name: docker  
  image: plugins/docker
  settings:
    dockerfile: db/
    username:
      from_secret: hub_username
    password:
      from_secret: hub_password
    repo: turik207/kube-db